adds `url.URL` wrapper and other improvements
projectdiscovery/utils pull request #47
Opened 2023-01-17 14:19 UTC by tarunKoyalwar

## Proposed Changes

closes #46

2023-01-17 15:03 UTC, xm1k3 approved these changes
lgtm

2023-01-17 15:15 UTC, tarunKoyalwar commented
@Ice3man543  , changed PR to draft until PR for nuclei is ready

2023-01-17 19:40 UTC, tarunKoyalwar commented
seems stable nothing to improve 
Ref: https://github.com/projectdiscovery/nuclei/pull/3211

2023-01-20 10:00 UTC, Mzack9999 requested changes
lgtm - suggesting `require` to make tests more concise

2023-01-20 10:00 UTC, Mzack9999 commented on url/merge_test.go
> +		if err != nil {
As in other packages we used `require` package. What do you think of using:
```go
require.Nil()
require.Equalf()
```

2023-01-20 12:28 UTC, tarunKoyalwar commented
## Changes

- bug fix where `localhost` was not considered as valid hostname

2023-01-23 09:33 UTC, Mzack9999 approved these changes

2023-01-23 09:33 UTC, merged